name: BlackHat-GHA-Demo
on: push
jobs:
  snyk-code-test-upload: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Snyk Code Upload test
        uses: snyk/actions/setup@master
        #continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --code --report --project-name=npm-js-goof-github-action --org=demo-i34 || true
          
  snyk-test-job:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Snyk test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --org=demo-i34
        
  snyk-monitor-job:
     needs: snyk-test-job
     runs-on: ubuntu-latest
     steps:
      - uses: snyk/actions/setup@master
      - uses: actions/checkout@master
      - name: Snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --all-projects --org=demo-i34
##################################################################
        
  Build-container-job:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@master
     - name: Build docker image
       run: docker build . --file=Dockerfile --tag example:1.0
       
  snyk-container-test-job:
     needs: Build-container-job
     runs-on: ubuntu-latest
     steps:
     - name: Snyk container test
       uses: snyk/actions/docker@master
       continue-on-error: true
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
         image: example:1.0
         #args: --container example:1.0
         
  snyk-container-monitor-job:
     needs: snyk-container-test-job
     runs-on: ubuntu-latest
     steps:
     - name: Snyk container monitor
       uses: snyk/actions/docker@master
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
         image: example:1.0
         command: monitor --org=demo-i34 --nested-jars-depth=5
         #args: --container monitor example:1.0
  ##################################################################
  #snyk-iac-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Snyk iac test
  #     uses: snyk/actions/iac@master
  #     continue-on-error: true
  #     env:
  #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  snyk-iac-test-report:
     #needs: snyk-iac-test
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@master
     - name: Snyk IAC
       uses: snyk/actions/iac@master
       continue-on-error: true
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
         args: --report --org=demo-i34
