name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@master

      - name: Install snyk-delta
        run: |
          npm i -g snyk-delta

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Just run Snyk-Delta pls  
      - run: snyk test --json --print-deps | snyk-delta
