name: Example workflow for Golang using Snyk
on: [push,pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: code --json-file-output=snyk.json
      
      - name: install snyk-to-html
        run: |
          npm install snyk-to-html -g
          cat snyk.json | snyk-to-html -o result.html
          ls -lrt
          pwd
          mkdir downloads
          cp -v /home/runner/work/java-goof/java-goof/*.html /home/runner/work/java-goof/java-goof/downloads
          
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: snyk-code results
          path: downloads
