name: snyk-labs action example - Snyk Issues to Github Issues
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install jira-tickets-new-vulns
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          sudo curl -LO 'https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/releases/download/1.25.0/snyk-jira-sync-linux'
          ls -l
          sudo chmod +x snyk-jira-sync-linux
          ls -l
        

 
